# Site settings
name: Todd's Lab
email: todd310378072@outlook.com
author: Todd Zhou
url: https://toddzhoufeng.github.io
resume_site: https://toddzhoufeng.github.io/
github: https://github.com/toddzhoufeng/
baseurl: ""
description: Shut up and just Try!
meta_description: 周镇峰;个人博客;学习与创造
motto: Life is a journey of exploration!
banner: 人生就是一团欲望,欲望不满便痛苦,满足了便无聊.人生就是在痛苦与无聊之间摇摆.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: toddzhoufeng

# Build settings
markdown: kramdown

baidu_analysis: 90a0f4831c8e2164534d62253a53088b
encoding: UTF-8
